source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-fix-react-native'

# inhibit_all_warnings!

target 'MobiusMobileWallet' do
  project 'MobiusMobileWallet', 'Debug' => :debug, 'Release' => :release
  platform :ios, '9.3'

  pod 'Fabric'
  pod 'Crashlytics'

  pod 'React', path: '../node_modules/react-native', subspecs: %W[
    Core
    CxxBridge
    DevSupport
    PrivateDatabase

    RCTActionSheet
    RCTAnimation
    RCTBlob
    RCTCameraRoll
    RCTImage
    RCTLinkingIOS
    RCTNetwork
    RCTSettings
    RCTText
    RCTWebSocket
    RCTVibration
  ]

  # Third-party dependencies required by React Native
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  # Add new pods below this line
  pod 'BVLinearGradient', path: '../node_modules/react-native-linear-gradient'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'ReactNativeFabric', path: '../node_modules/react-native-fabric'
  pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'
  pod 'RNKeychain', path: '../node_modules/react-native-keychain'
  pod 'RNLanguages', path: '../node_modules/react-native-languages'
  pod 'RNSVG', path: '../node_modules/react-native-svg'
  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons', subspecs: %W[
    MaterialIcons
    MaterialCommunityIcons
    FontAwesome
  ]

  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-randombytes', path: '../node_modules/react-native-randombytes'
  pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  target 'MobiusMobileWalletTests' do
    inherit! :search_paths

    pod 'React/RCTTest', path: '../node_modules/react-native'
  end
end

# Some react-native-* deps have their deployment target set to < 8.0 which
# generates some warning in Xcode 9+. Since the Pod project itself will
# have deployment target specified (we control it with `platform` setting
# above), the easiest solution is to delete deployment target configuration
# from all its targets, so that they inherit configuration from a project.
post_install do |lib|
  lib.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
