source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
plugin 'cocoapods-fix-react-native'
plugin 'cocoapods-keys',
  project: "MobiusMobileWallet",
  keys: %w(CrashlyticsAPIToken CrashlyticsBuildSecret)

inhibit_all_warnings!

target 'MobiusMobileWallet' do
  pod 'React', path: '../node_modules/react-native', subspecs: %W[
    Core
    CxxBridge
    DevSupport
    PrivateDatabase

    RCTActionSheet
    RCTAnimation
    RCTBlob
    RCTImage
    RCTLinkingIOS
    RCTNetwork
    RCTPushNotification
    RCTSettings
    RCTText
    RCTWebSocket
    RCTVibration
  ]

  # Third-party dependencies required by React Native
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'



  # Add new pods below this line

  pod 'BVLinearGradient', path: '../node_modules/react-native-linear-gradient'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'ReactNativeFabric', path: '../node_modules/react-native-fabric'
  pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'
  pod 'RNI18n', path: '../node_modules/react-native-i18n'
  pod 'RNKeychain', path: '../node_modules/react-native-keychain'
  pod 'RNSVG', path: '../node_modules/react-native-svg'
  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-randombytes', path: '../node_modules/react-native-randombytes'
  pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'
  pod 'react-native-udp', :path => '../node_modules/react-native-udp'
  pod 'react-native-tcp', :path => '../node_modules/react-native-tcp'
  pod 'react-native-os', :path => '../node_modules/react-native-os'


  target 'MobiusMobileWalletTests' do
    inherit! :search_paths

    pod 'React/RCTTest', path: '../node_modules/react-native'
  end
end

post_install do |installer|
    # Pod project template has some overly strict build settings by default,
    # which don't play nicely with react-native core components and libs.

    extra_settings = %W[
      CLANG_ANALYZER_NONNULL
      CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION
      CLANG_ENABLE_OBJC_WEAK
      CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING
      CLANG_WARN_COMMA
      CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS
      CLANG_WARN_DOCUMENTATION_COMMENTS
      CLANG_WARN_INFINITE_RECURSION
      CLANG_WARN_NON_LITERAL_NULL_CONVERSION
      CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF
      CLANG_WARN_OBJC_LITERAL_CONVERSION
      CLANG_WARN_RANGE_LOOP_ANALYSIS
      CLANG_WARN_STRICT_PROTOTYPES
      CLANG_WARN_SUSPICIOUS_MOVE
      CLANG_WARN_UNGUARDED_AVAILABILITY
      GCC_NO_COMMON_BLOCKS
    ]
    installer.pods_project.build_configurations.each do |config|
      extra_settings.each do |setting|
        config.build_settings.delete(setting)
      end
    end
end
